{% set python_min = '3.10' %}
{% set name = "symbolite" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/symbolite-{{ version }}.tar.gz
  sha256: b7a576eb61131feac9e74a9da6fae0f110beaa537667575b143f50eac424b7f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - symbolite
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hgrecco/symbolite
  summary: A minimalistic symbolic package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maurosilber
    - hgrecco
