{% set python_min = "3.10" %}
{% set name = "symbolite" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/symbolite-{{ version }}.tar.gz
  sha256: 6baadaa9d5707baf54102f7d2076c307875b4f4ae2c760bbd38b555dafe98ef8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - symbolite
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hgrecco/symbolite
  summary: A minimalistic symbolic package.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maurosilber
    - hgrecco
